In [1077]:
import torch
import torch.nn as nn
from sklearn.model_selection import train_test_split
from torch.utils.data import Dataset, DataLoader
import pandas as pd
import re

In [1078]:
device = ('cuda' if torch.cuda.is_available() else 'cpu')

In [1079]:
device

'cuda'

In [1080]:
train_dataset = pd.read_csv("train.csv", encoding="latin1")
test_dataset = pd.read_csv("test.csv", encoding="latin1")

In [1081]:
train_dataset.columns

Index(['textID', 'text', 'selected_text', 'sentiment', 'Time of Tweet',
       'Age of User', 'Country', 'Population -2020', 'Land Area (Km²)',
       'Density (P/Km²)'],
      dtype='object')

In [1082]:
train_dataset.head()

,textID,text,selected_text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Km²),Density (P/Km²)
0,cb774db0d1,"I`d have responded, if I were going","I`d have responded, if I were going",neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,549e992a42,Sooo SAD I will miss you here in San Diego!!!,Sooo SAD,negative,noon,21-30,Albania,2877797,27400.0,105
2,088c60f138,my boss is bullying me...,bullying me,negative,night,31-45,Algeria,43851044,2381740.0,18
3,9642c003ef,what interview! leave me alone,leave me alone,negative,morning,46-60,Andorra,77265,470.0,164
4,358bd9e861,"Sons of ****, why couldn`t they put them on t...","Sons of ****,",negative,noon,60-70,Angola,32866272,1246700.0,26

In [1083]:
test_dataset.columns

Index(['textID', 'text', 'sentiment', 'Time of Tweet', 'Age of User',
       'Country', 'Population -2020', 'Land Area (Kmï¿½)',
       'Density (P/Kmï¿½)'],
      dtype='object')

In [1084]:
test_dataset.head()

,textID,text,sentiment,Time of Tweet,Age of User,Country,Population -2020,Land Area (Kmï¿½),Density (P/Kmï¿½)
0,f87dea47db,Last session of the day http://twitpic.com/67ezh,neutral,morning,0-20,Afghanistan,38928346,652860.0,60
1,96d74cb729,Shanghai is also really exciting (precisely -...,positive,noon,21-30,Albania,2877797,27400.0,105
2,eee518ae67,"Recession hit Veronique Branquinho, she has to...",negative,night,31-45,Algeria,43851044,2381740.0,18
3,01082688c6,happy bday!,positive,morning,46-60,Andorra,77265,470.0,164
4,33987a8ee5,http://twitpic.com/4w75p - I like it!!,positive,noon,60-70,Angola,32866272,1246700.0,26

In [1085]:
train_dataset = train_dataset.loc[:,["text", "sentiment"]]

In [1086]:
test_dataset = test_dataset.loc[:, ["text", "sentiment"]]

In [1087]:
train_dataset.head()

                                                text sentiment
0                I`d have responded, if I were going   neutral
1      Sooo SAD I will miss you here in San Diego!!!  negative
2                          my boss is bullying me...  negative
3                     what interview! leave me alone  negative
4   Sons of ****, why couldn`t they put them on t...  negative

In [1088]:
test_dataset.head()

                                                text sentiment
0  Last session of the day  http://twitpic.com/67ezh   neutral
1   Shanghai is also really exciting (precisely -...  positive
2  Recession hit Veronique Branquinho, she has to...  negative
3                                        happy bday!  positive
4             http://twitpic.com/4w75p - I like it!!  positive

In [1089]:
train_dataset.shape

(27481, 2)

In [1090]:
def tokenizer(text):
    text = str(text)
    lower_case_text = text.lower()
    # removes the characters that are not letter or digit or space with ""
    text = re.sub(r"[^\w\d\s]", "", lower_case_text)
    return text.split()

In [1091]:
tokenizer("Hello MY NaMe is AbhIHsheK TimMsInA")

['hello', 'my', 'name', 'is', 'abhihshek', 'timmsina']

In [1092]:
tokenizer(train_dataset.iloc[0,0])

['id', 'have', 'responded', 'if', 'i', 'were', 'going']

In [1093]:
answers = {}
choices = train_dataset.iloc[:, 1].unique()
print(choices)
for i in choices:
    answers[i] = len(answers)
answers

['neutral' 'negative' 'positive']

{'neutral': 0, 'negative': 1, 'positive': 2}

In [1094]:
# voccabulary for stroing the tokens
voccab = {
    '<UNK>' : 0
}

# for building the voccabulary for training as it is done in timestep, each token means one timestep
def build_voccab(dataset):
    for text_index in range(dataset.shape[0]):
        text = dataset.iloc[text_index,0]
        # tokenize
        tokens = tokenizer(text)
        # add in voccab
        for token in tokens:
            if token not in voccab:
                voccab[token] = len(voccab)
    print("voccab created ✅")

In [1095]:
build_voccab(train_dataset)

voccab created ✅

In [1096]:
len(voccab)

29584

In [1097]:
def text_to_indices(text, voccab):
    tokens = tokenizer(text)
    indices = []
    if len(tokens) == 0:
        indices.append(voccab['<UNK>'])
        return torch.tensor(indices)
    for token in tokens:
        if token in voccab:
            indices.append(voccab[token])
        else:
            indices.append(voccab["<UNK>"])
    return torch.tensor(indices)

In [1098]:
indices = text_to_indices("i am dsd", voccab)
indices

tensor([  5, 112,   0])

In [1099]:
len(voccab)

29584

In [1100]:
# location where the data are stored
class CustomDataSet(Dataset):
    def __init__(self, df, voccab):
        self.df = df
        self.voccab = voccab
        print(self.df.shape)
        print(len(self.voccab))

    def __len__(self):
        return self.df.shape[0]

    def __getitem__(self, index):
        indices = text_to_indices(self.df.iloc[index, 0], self.voccab)
        answer = torch.tensor(answers[self.df.iloc[index, 1]])
        return indices, answer

In [1101]:
train_data = CustomDataSet(train_dataset, voccab)

(27481, 2)
29584

In [1102]:
train_data.__getitem__(0)

(tensor([1, 2, 3, 4, 5, 6, 7]), tensor(0))

In [1103]:
train_dataloader = DataLoader(dataset = train_data, batch_size = 64, shuffle = True)

In [1104]:
len(train_dataloader)

430

In [1108]:
class RNN(nn.Module):
    def __init__(self, size_of_voccab, size_of_embedding):

        super().__init__()
        
        # embedding so that the model can understand the tokens as the integer is nothing but id
        # we need a embedding that explains the meaning of the token to the rnn
        # as the model learns, the embedding also improves
        self.embedding = nn.Embedding(num_embeddings= size_of_voccab, embedding_dim= size_of_embedding)
        # RNN as the sequential model, that process the embedding of each token sequentially and understands/learns/summarizes the tokens one timestep at a time
        # it uses the backward loop to use previous hidden state in the hidden layer of next time step as context/memroy to process the nextt token
        # with such mechanism it keeps summarizing till the end and
        # it gives 64 output by taking embedding of each token
        self.rnn = nn.RNN(size_of_embedding, 64)
        # linear is used to combine the output into 3 neurons(positive, negative and neutral)
        self.linear = nn.Linear(64, 3)

    # Forward Propagation
    def forward(self, tokens_indices):
        embeddings = self.embedding(tokens_indices)
        rnn_output = self.rnn(embeddings)
        linear = self.linear(rnn_output[1])
        return linear

In [1109]:
rnn_model = RNN(len(voccab), 50)
rnn_model.to(device=device)

RNN(
  (embedding): Embedding(29584, 50)
  (rnn): RNN(50, 64)
  (linear): Linear(in_features=64, out_features=3, bias=True)
)

In [1110]:
train_data[0]

(tensor([1, 2, 3, 4, 5, 6, 7]), tensor(0))

In [1111]:
for i in rnn_model.named_parameters():
    print(i)

('embedding.weight', Parameter containing:
tensor([[ 1.0692,  1.0807,  1.2554,  ..., -1.3476,  0.6221, -1.8506],
        [ 1.0206,  0.4352, -0.4132,  ..., -0.6703, -0.7866,  0.3732],
        [ 0.3996, -0.2840, -0.2731,  ...,  0.7837,  0.2047, -1.9735],
        ...,
        [ 0.6666, -1.6364, -0.7351,  ..., -1.4142,  2.1852,  0.7464],
        [ 0.3243,  0.4817, -0.3267,  ...,  0.6472,  0.7841, -0.1572],
        [-0.5624,  0.2795, -1.2253,  ..., -0.0817, -0.3387, -0.1879]],
       device='cuda:0', requires_grad=True))
('rnn.weight_ih_l0', Parameter containing:
tensor([[ 0.1070, -0.0211,  0.0659,  ..., -0.1209,  0.0525, -0.0922],
        [-0.1149,  0.1098, -0.0940,  ..., -0.0060,  0.0349,  0.0404],
        [ 0.1049, -0.0551, -0.0013,  ...,  0.0801,  0.0340, -0.0511],
        ...,
        [ 0.0366, -0.0597,  0.1047,  ...,  0.1198, -0.0913,  0.0551],
        [-0.0070, -0.0154,  0.0970,  ...,  0.0124,  0.0737, -0.0457],
        [ 0.0641,  0.0257,  0.0150,  ...,  0.1066,  0.0745, -0.1038]],
       device='cuda:0', requires_grad=True))
('rnn.weight_hh_l0', Parameter containing:
tensor([[ 0.0276,  0.1201,  0.0454,  ...,  0.0572, -0.0615,  0.0237],
        [-0.0660, -0.0159,  0.1178,  ...,  0.0931,  0.0343,  0.1205],
        [-0.0752, -0.1061, -0.0200,  ...,  0.0010,  0.0274, -0.0944],
        ...,
        [-0.0626,  0.0312,  0.0066,  ..., -0.0399,  0.0807,  0.0228],
        [ 0.0705,  0.0744, -0.0551,  ..., -0.0726,  0.0953, -0.0465],
        [ 0.0648, -0.0781,  0.0971,  ...,  0.0170,  0.0247, -0.0756]],
       device='cuda:0', requires_grad=True))
('rnn.bias_ih_l0', Parameter containing:
tensor([-0.0801,  0.1170,  0.0468, -0.0299, -0.1004,  0.0123,  0.0549, -0.1085,
         0.0211, -0.0106, -0.0925, -0.0735,  0.0124,  0.1244,  0.0632, -0.1146,
        -0.0770,  0.0857,  0.0527, -0.1196,  0.0322,  0.0484, -0.0680,  0.1053,
         0.0992,  0.1151, -0.1097, -0.0956,  0.1181,  0.1147, -0.0076,  0.1227,
         0.0003, -0.1159, -0.0603,  0.1077,  0.0126,  0.0474, -0.1193, -0.0843,
         0.0760,  0.1001, -0.0399, -0.0210, -0.0510, -0.0253,  0.1065, -0.1150,
        -0.1027,  0.0909,  0.0038, -0.0082,  0.0415, -0.0703, -0.0259, -0.0254,
         0.0919,  0.0022, -0.0072, -0.1077,  0.1185, -0.0038,  0.0373,  0.0825],
       device='cuda:0', requires_grad=True))
('rnn.bias_hh_l0', Parameter containing:
tensor([ 0.0720,  0.0692,  0.0383,  0.0722, -0.0661, -0.0087, -0.0479,  0.0327,
         0.1103,  0.0144, -0.1123,  0.0057,  0.1048,  0.0658, -0.0568, -0.0785,
         0.0806,  0.0790, -0.0355,  0.0654,  0.0601,  0.0704,  0.0636,  0.1064,
         0.0112,  0.0382, -0.0670,  0.0794,  0.1161, -0.0804, -0.1108, -0.0808,
        -0.1015,  0.0729, -0.0917, -0.0311, -0.0273, -0.0225, -0.0376, -0.0205,
        -0.0936, -0.0620,  0.0865, -0.0616, -0.1209, -0.1213, -0.0777, -0.0338,
         0.1024, -0.1084, -0.0693,  0.0033, -0.0403, -0.1114, -0.0041, -0.0368,
        -0.0331,  0.0039,  0.0224, -0.1060, -0.0820,  0.0131, -0.1004, -0.1137],
       device='cuda:0', requires_grad=True))
('linear.weight', Parameter containing:
tensor([[-0.0394,  0.0602, -0.0664,  0.0688, -0.0642,  0.0994, -0.0281,  0.1004,
         -0.0600, -0.0322,  0.0730,  0.1129, -0.0505, -0.0423, -0.0761,  0.0166,
         -0.1168,  0.0130, -0.0668,  0.1229, -0.0586, -0.0968, -0.0245,  0.0230,
         -0.1209,  0.0481,  0.0636, -0.0667,  0.0313,  0.0544, -0.1155, -0.1127,
         -0.0809,  0.0362,  0.0588, -0.0876, -0.0486, -0.0948, -0.0012, -0.0708,
         -0.0144, -0.0948,  0.0081, -0.0324, -0.1180, -0.0003, -0.1015, -0.0108,
          0.0324, -0.0969,  0.1249,  0.1213,  0.0025,  0.1080,  0.0732, -0.0737,
         -0.0452, -0.0818, -0.0317, -0.0344,  0.0532,  0.0881, -0.0379, -0.0362],
        [-0.0551, -0.0790,  0.0950, -0.0083, -0.0816, -0.0899, -0.0535,  0.0428,
         -0.0335,  0.0652,  0.0447,  0.1003, -0.0423, -0.0208,  0.0973, -0.0787,
         -0.0531,  0.1120, -0.0279,  0.0379, -0.1026, -0.0693, -0.0999,  0.0022,
         -0.0515, -0.1235, -0.0687,  0.1241, -0.0962, -0.0963,  0.0271, -0.0169,
          0.0013,  0.0166, -0.0225, -0.0729,  0.0591,  0.0928,  0.1011, -0.0805,
          0.0817,  0.0730, -0.0603,  0.0605,  0.0500, -0.0535, -0.1047, -0.0462,
         -0.1173, -0.0077, -0.0664,  0.0838, -0.1027, -0.1245,  0.0049,  0.0849,
          0.0118,  0.1217, -0.0305,  0.0518,  0.0937, -0.0653,  0.0848,  0.0655],
        [ 0.0850,  0.0634,  0.0571, -0.0034, -0.0017,  0.1131, -0.0575,  0.0207,
          0.0266,  0.0081,  0.0321, -0.0457, -0.0546, -0.0279,  0.0651, -0.1126,
          0.0072,  0.0407,  0.0427,  0.1001, -0.0456,  0.0802,  0.0229,  0.1222,
         -0.1052,  0.0042, -0.0671,  0.0901,  0.0588,  0.0087,  0.0251, -0.0444,
         -0.1159,  0.0060, -0.0228, -0.0944,  0.0686,  0.0106,  0.1198,  0.0148,
         -0.0743,  0.0167, -0.0048, -0.0496, -0.1126, -0.0607, -0.1114, -0.0593,
          0.1186,  0.0932, -0.0875, -0.0528,  0.0039,  0.0135, -0.0550,  0.1190,
          0.1098, -0.0894,  0.1061,  0.0612,  0.1195, -0.0368,  0.1225,  0.0392]],
       device='cuda:0', requires_grad=True))
('linear.bias', Parameter containing:
tensor([ 0.0860,  0.1009, -0.0279], device='cuda:0', requires_grad=True))

In [1112]:
loss_fn = nn.CrossEntropyLoss()
optim = torch.optim.Adam(rnn_model.parameters(), lr = 0.001)

In [1113]:
epochs = 25

In [ ]:
# training the RNN model:
for epoch in range(epochs):
    tota_loss = 0
    for que, ans in train_dataloader:
        que = que.reshape(que.shape[1]).to(device)
        ans = ans.to(device)
        y_pred = rnn_model(que)
        optim.zero_grad()
        loss = loss_fn(y_pred, ans)
        loss.backward()
        optim.step()
        tota_loss = tota_loss + loss.item()
    print("Epoch :", epoch, "===============  Loss :", tota_loss/len(train_dataloader))

In [1114]:
tokens = tokenizer(test_dataset.iloc[4, 0])
tokens

['httptwitpiccom4w75p', 'i', 'like', 'it']

In [1115]:
index = text_to_indices(tokens, voccab).to(device=device)
index

tensor([  0,   5,  88, 133], device='cuda:0')

In [1116]:
rnn_model(index)

tensor([[-0.2737,  0.2582, -0.2757]], device='cuda:0',
       grad_fn=<AddmmBackward0>)

In [1117]:
test_dataset.shape

(3534, 2)

## testing using the test

In [1118]:
test_data = CustomDataSet(test_dataset, voccab)
test_dataloader = DataLoader(test_data, batch_size= 1, shuffle= False)

(3534, 2)
29584

In [1119]:
test_data.__len__()

3534

In [1120]:
test_data[1]

(tensor([    0,    19,   374,    87,  1476, 13469,     0, 16109,   454,  5523,
            14,  5780, 13200,     0]),
 tensor(2))

In [1121]:
rnn_model.eval()

RNN(
  (embedding): Embedding(29584, 50)
  (rnn): RNN(50, 64)
  (linear): Linear(in_features=64, out_features=3, bias=True)
)

In [1122]:
correct = 0
for question, answer in test_dataloader:
    question = question.reshape(question.shape[1]).to(device)
    answer = answer.to(device)
    y_pred = rnn_model(question)
    if answer == torch.max(y_pred, dim= 1)[1]:
        correct = correct + 1
    print("real :", answer)
    print(y_pred)
    print("pred :", torch.max(y_pred, dim = 1)[1])
    print("="*100)
print("Accuracy :", correct/len(test_dataloader))

real : tensor([0], device='cuda:0')
tensor([[-0.2598, -0.0441, -0.0953]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.5137,  0.0172, -0.1615]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.0304, -0.2036,  0.1550]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[0.0250, 0.1772, 0.2616]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.2737,  0.2582, -0.2757]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.5595, -0.2055,  0.1967]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.0599, -0.2801, -0.0402]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.3543,  0.0301,  0.1279]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1668,  0.4073,  0.1210]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.0930, -0.2228, -0.2991]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.2111, -0.1481, -0.0013]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.2226, 0.3816, 0.1859]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.4016, 0.1581, 0.3667]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.2517, -0.1874, -0.1031]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.1324,  0.1446,  0.2084]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.0929,  0.5385, -0.1748]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.2874,  0.3312,  0.4930]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.0161,  0.2241, -0.1500]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[0.2334, 0.6210, 0.4474]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.1237, 0.5749, 0.3537]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[0.0588, 0.0315, 0.1722]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.0223,  0.4451, -0.0754]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.4763,  0.0563, -0.1291]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.0902, -0.2993,  0.1306]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[0.2628, 0.7176, 0.3517]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.2061, -0.2825,  0.1772]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.1052, 0.3368, 0.3682]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.2056,  0.4221, -0.2526]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.4326,  0.1887, -0.0464]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.0218,  0.1702, -0.0382]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1814, -0.5237,  0.0206]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.0655,  0.0511, -0.0718]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.0141,  0.0668, -0.2542]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.0707, 0.3028, 0.5598]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.5945,  0.1238, -0.0356]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[0.0695, 0.0201, 0.1231]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[0.1882, 0.0198, 0.0156]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.0362, 0.0460, 0.0132]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.1704, -0.2729, -0.0201]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.3296, -0.4044, -0.1766]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.3370, -0.1520,  0.4418]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1778, -0.1445, -0.1436]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.4140, -0.0854, -0.3180]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.0312, 0.0331, 0.1332]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.1676, -0.4102,  0.4466]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.0722, -0.2303,  0.3394]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.3384, 0.1840, 0.0666]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.1889, -0.1923,  0.0627]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.5290,  0.0186, -0.0679]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.1466,  0.0329, -0.4451]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.2678,  0.2206, -0.0305]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.1737, 0.0655, 0.0673]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.1566,  0.1743, -0.1625]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.3700, -0.0963, -0.1925]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1197,  0.4009,  0.4251]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.1521, -0.1339,  0.0859]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.4085, -0.0761, -0.3264]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.2792,  0.4509, -0.0226]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.4418, 0.3259, 0.2376]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[0.1886, 0.0855, 0.1019]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.0778, -0.2048, -0.3937]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1821,  0.0059, -0.2122]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.4758, -0.4184, -0.3321]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.0299, -0.0964, -0.0364]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.2070,  0.2597, -0.0186]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.0510, -0.1884,  0.0427]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.3361,  0.1256, -0.2450]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.0798, 0.6010, 0.0680]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([1], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[0.1904, 0.1191, 0.3528]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[ 0.0346, -0.5659,  0.0381]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[-0.0582,  0.0939,  0.4332]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.1001, -0.2241, -0.3010]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[-0.1489, -0.2685,  0.1597]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([0], device='cuda:0')
tensor([[0.2283, 0.3303, 0.7751]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([2], device='cuda:0')
tensor([[ 0.0132, -0.4371,  0.3585]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[ 0.1021, -0.2867, -0.0866]], device='cuda:0',
       grad_fn=<AddmmBackward0>)
pred : tensor([0], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[0.0350, 0.5055, 0.5839]], device='cuda:0', grad_fn=<AddmmBackward0>)
pred : tensor([2], device='cuda:0')
====================================================================================================
real : tensor([1], device='cuda:0')
tensor([[-0.3862, -0.0485, -0.0471]], device='cuda:0',